### ISSUE TITLE
Enable Style/HashSyntax Ruby 1.9

### ISSUE THREAD

**Issue by PanosCodes** [Apipie/apipie-rails#813]
## Motivation
Across the Apipie code base there different ways of using hashes. For consistency reasons. I think we could standardize that.

## Proposal
Although that's a personal preference I think we could use the Ruby 1.9 style of Hash syntax and have Symbol keys use `:` as well as String keys use `=>`

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax

Example
```ruby
# bad
{:a => 2}
{b: 1, :c => 2}

# good
{a: 2, b: 1}
{:c => 2, 'd' => 2} # acceptable since 'd' isn't a symbol
{d: 1, 'e' => 2} # technically not forbidden
```

## Implementation
In `.rubocop.yml` we can enable the `Style/HashSyntax` rule and run the autocorrector(Can Rubocop challenger do that ?)
```yml
Style/HashSyntax:
  EnforcedStyle: ruby19
```

___
Any thoughts ?

**Comment by mathieujobin** [comment]
When I had to take such a decision in the past, it was for trailing or leading dots for multiline method calls.

```
Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  StyleGuide: '#consistent-multi-line-chains'
  EnforcedStyle: trailing
```

it was a large code base, and so I tried to do the auto-correct with both settings and chose the one with the least changes. so to keep the code base as consistent as possible.

if its half and half, I'd be tempted only to enforce on new files toward the preference the team has.
