### ISSUE TITLE
Swagger 2: Components Response `required: true` is not valid swagger 

### ISSUE THREAD

**Issue by simonireilly** [Apipie/apipie-rails#941]
## Description

Path parameters are singleton resources, and have the schema of `required: true` to specify their _require_ment

```
paths:
  /users/{userId}:
    get:
      summary: Get a user by ID
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
```

Schema response components and request bodies use the `required: []` syntax to specify which of the fields in their object structure must be provided.

## Fix

When generating swagger from ApiPie remove the `required: true` generated output from the JSON for request bodies and response bodies, but preserve the array definition
